### ISSUE TITLE
feature request: implement areas of interest

### ISSUE THREAD

**Issue by silberzwiebel** [jashubbard/edfR_test#3]
Hi, 

it would be really great if this package could use defined interest areas and compute the number of fixations that fall into an interest area during a time duration.
I'm picturing something like this at the moment:

```
> edf.getFixationsInInterestArea(edf.file, interestArea, from = 300, to = 900)
36
```

Best,
silberzwiebel

**Comment by tmalsburg** [comment]
I agree regarding the areas of interest, and I have code somewhere that can do this.  However, I'd rather not add support for computing specific dependent variables because there are so many different DVs that could be added and there are already packages that calculate DVs (e.g., em2).  Also, once we have areas of interest, calculating the number of fixations on an area is a one-liner.

**Comment by jashubbard** [comment]
I've split that sort of functionality into a separate package: https://github.com/jashubbard/itrackR . It is a work in progress, but it should be perfectly capable of doing what you need. By design we are keeping edfR pretty lean, so it's really just about importing the EDF data. Everything else I'm putting into itrackR.

**Comment by silberzwiebel** [comment]
Perfect, thanks. `itrackR` looks great! May I suggest you add a hint to `itrackR` in the README of `edfR`?
